### ISSUE TITLE
Naming of this library

### ISSUE THREAD

**Issue by johsoe** [nodes-android/nEncrypt#2]
We might need to tweak the name a bit, suggestions are welcome:

**Comment by johsoe** [comment]
nEncrypt

**Comment by johsoe** [comment]
nCrypt

**Comment by vovahost** [comment]
ssafe

**Comment by johsoe** [comment]
Following on @biscon medieval theme:

Padlock
Locksmith
Shackle
Chest

**Comment by vovahost** [comment]
NodeLock, NodeSafe

**Comment by johsoe** [comment]
Strongbox

**Comment by Muddz** [comment]
ByteSafe/BitSafe
NodeVault/VaultN14
N14 (N is the 14'th in the alphabet)

**Comment by BrianEstrada** [comment]
library has been named!
